const data = [
    {
        id: 1,
        name: "Chocolate Lava Cake",
        category: "dessert",
        restaurant: "Sweet Tooth Bakery",
        review: 124,
        stars: 5,
        distance_km: 2.3,
        travel_time: 15,
        image: "/images/chocolate-lava-cake.jpg",
        price: 7.99,
    },
    {
        id: 2,
        name: "Margherita Pizza",
        category: "italian food",
        restaurant: "Little Italy",
        review: 230,
        stars: 4,
        distance_km: 3.1,
        travel_time: 18,
        image: "/images/margherita-pizza.jpg",
        price: 10.99,
    },
    {
        id: 3,
        name: "Cheeseburger",
        category: "fast food",
        restaurant: "Burger Hub",
        review: 340,
        stars: 4,
        distance_km: 1.2,
        travel_time: 10,
        image: "/images/cheese-burger.jpg",
        price: 8.49,
    },
    {
        id: 4,
        name: "Sushi Platter",
        category: "asian food",
        restaurant: "Tokyo Bites",
        review: 189,
        stars: 5,
        distance_km: 4.5,
        travel_time: 20,
        image: "/images/sushi-platter.jpg",
        price: 15.99,
    },
    {
        id: 5,
        name: "BBQ Ribs",
        category: "barbecue",
        restaurant: "Grill Master",
        review: 98,
        stars: 4,
        distance_km: 5.8,
        travel_time: 25,
        image: "/images/bbq-ribs.jpg",
        price: 18.99,
    },
    {
        id: 6,
        name: "Tiramisu",
        category: "dessert",
        restaurant: "Dolce Vita",
        review: 210,
        stars: 5,
        distance_km: 3.0,
        travel_time: 15,
        image: "/images/tiramisu.jpg",
        price: 6.99,
    },
    {
        id: 7,
        name: "Pad Thai",
        category: "asian food",
        restaurant: "Bangkok Street",
        review: 156,
        stars: 4,
        distance_km: 2.6,
        travel_time: 13,
        image: "/images/pad-thai.jpg",
        price: 12.49,
    },
    {
        id: 8,
        name: "Pepperoni Pizza",
        category: "italian food",
        restaurant: "Pasta Paradise",
        review: 305,
        stars: 4,
        distance_km: 3.3,
        travel_time: 17,
        image: "/images/papperoni-pizza.jpg",
        price: 11.49,
    },
    {
        id: 9,
        name: "Fried Chicken",
        category: "fast food",
        restaurant: "Crispy Chicken",
        review: 450,
        stars: 5,
        distance_km: 1.0,
        travel_time: 8,
        image: "/images/fried-chicken.jpg",
        price: 7.49,
    },
    {
        id: 10,
        name: "Apple Pie",
        category: "dessert",
        restaurant: "Pie Corner",
        review: 145,
        stars: 4,
        distance_km: 2.9,
        travel_time: 16,
        image: "/images/apple-pie.jpg",
        price: 5.99,
    },
];

export default data;
